from pathlib import Path
import json
import re

ROOT = Path(__file__).parents[1]
DATE = "2026-09-28"
IMAGE = "/thumbnails/multi-location-appointment-routing-guide.svg"

items = [
    dict(slug="bilingual-call-routing-language-preference-handoff", title="Bilingual call routing: capture language preference without overstating coverage", category="call-routing", audience="multi-location service businesses", request="a caller asks to continue in a language the first receptionist does not confidently speak", fields="the caller's preferred spoken language, callback number, service location, reason for calling, safe callback window, and whether an interpreter is already present", boundary="claiming fluency, using an unapproved relative for sensitive interpretation, or translating a technical, legal, clinical, or pricing decision", owner="the approved bilingual queue or contracted interpreter coordinator", scenario="A caller begins in English, then asks for Spanish when describing a billing dispute. The receptionist records the preference and the neutral purpose of the call, avoids debating the charge, and routes the record to the approved Spanish-language billing queue.", source="https://www.hhs.gov/civil-rights/for-individuals/special-topics/limited-english-proficiency/index.html", source_name="HHS limited-English-proficiency resources"),
    dict(slug="property-restoration-emergency-call-intake", title="Property restoration emergency calls: separate hazards from dispatch facts", category="field-service-intake", audience="water, fire, and storm restoration companies", request="a property owner reports active damage and wants a crew dispatched immediately", fields="caller location, affected address, safe callback number, observed water or smoke, whether occupants are in immediate danger, utility status as reported, access constraints, and insurer contact if available", boundary="telling anyone to enter an unsafe structure, diagnosing contamination, promising arrival time, or confirming insurance coverage", owner="the on-call restoration dispatcher", scenario="A tenant reports water entering through a ceiling near a light fixture. The receptionist uses the company's emergency script, tells the caller to follow the approved emergency direction, records only observed conditions, and escalates without suggesting electrical or structural work.", source="https://www.ready.gov/home-fires", source_name="Ready.gov home-fire guidance"),
    dict(slug="elevator-entrapment-service-call-routing", title="Elevator entrapment calls: confirm location, escalate, and preserve the record", category="emergency-intake", audience="elevator maintenance providers and property managers", request="a caller says people are unable to exit an elevator car", fields="building name, street address, elevator identifier, floor indicator if visible, number of occupants as reported, reported medical distress, callback number, and the party already contacted", boundary="giving mechanical release instructions, asking occupants to force doors, estimating rescue time, or treating a service ticket as proof that emergency help is coming", owner="the emergency dispatch role named in the building's approved entrapment procedure", scenario="A security guard reports two occupants in car three and says one sounds short of breath. The receptionist confirms the exact building and car, follows the emergency escalation map, records who acknowledged the call, and does not troubleshoot the elevator.", source="https://www.osha.gov/laws-regs/regulations/standardnumber/1917/1917.116", source_name="OSHA elevator safety standard"),
    dict(slug="hvac-refrigerant-leak-call-boundaries", title="HVAC refrigerant leak calls: useful intake without remote diagnosis", category="field-service-intake", audience="HVAC contractors", request="a customer reports an odor, hissing, loss of cooling, or concern about a refrigerant leak", fields="service address, equipment type if known, symptoms the caller directly observed, when they began, occupancy concerns, prior service reference, access window, and callback number", boundary="identifying a substance by phone, giving exposure treatment, instructing an untrained caller to open equipment, or promising a particular repair", owner="the licensed-service dispatcher or designated safety reviewer", scenario="A restaurant manager hears hissing near a walk-in unit after closing. The receptionist records the observation and location, applies the contractor's approved safety escalation, and avoids stating that refrigerant is the cause.", source="https://www.epa.gov/section608", source_name="EPA Section 608 resources"),
    dict(slug="fire-sprinkler-impairment-service-call-intake", title="Fire sprinkler impairment calls: route urgent facts without making the safety decision", category="emergency-intake", audience="fire protection service companies", request="a building contact reports a closed valve, alarm, leak, damaged head, or system placed out of service", fields="site address, caller role, affected system or area as stated, visible discharge, alarm-panel wording, occupancy status, fire department contact status, and callback number", boundary="declaring a building safe, directing valve operation, silencing an alarm, approving a fire watch, or deciding whether evacuation is required", owner="the fire-protection company's emergency service coordinator", scenario="A warehouse supervisor reports a damaged sprinkler head and active discharge in one aisle. The receptionist captures the exact location and observed condition, follows the emergency notification script, and leaves system control to authorized responders.", source="https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.159", source_name="OSHA automatic-sprinkler standard"),
    dict(slug="title-company-payoff-request-call-intake", title="Title company payoff request calls: verify the request before moving documents", category="professional-services-intake", audience="title and settlement companies", request="a borrower, lender, or settlement contact asks for a mortgage payoff amount or document status", fields="caller identity, represented organization, property reference, loan reference through the approved channel, requested good-through date, authorization status, secure delivery method, and closing deadline", boundary="disclosing loan details before verification, calculating a payoff, accepting wiring instructions in ordinary notes, or promising that a statement will arrive by a particular time", owner="the verified payoff-processing or settlement role", scenario="A caller claiming to represent a lender asks that a payoff statement be emailed to a new address. The receptionist records the request but does not change delivery details; the authorized processor verifies the contact through the established channel.", source="https://www.consumerfinance.gov/ask-cfpb/how-do-i-get-a-payoff-amount-for-my-mortgage-loan-en-205/", source_name="CFPB mortgage-payoff explainer"),
    dict(slug="water-utility-service-interruption-call-intake", title="Water service interruption calls: build an outage record customers can trust", category="public-service-intake", audience="water utilities and contracted customer-service teams", request="a resident or business reports no water, low pressure, discoloration, or a suspected main break", fields="service address, callback number, time first noticed, whether neighboring properties are affected, visible street conditions, customer vulnerability flag allowed by policy, and prior notice reference", boundary="declaring water safe to drink, interpreting a health symptom, predicting restoration time without an approved update, or telling a caller to operate utility equipment", owner="the utility operations desk or approved after-hours duty officer", scenario="Several callers on one block report low pressure while one sees water in the roadway. The receptionist links the reports by location, preserves each observation separately, and shares only the outage status approved by operations.", source="https://www.epa.gov/ground-water-and-drinking-water/emergency-response-drinking-water-and-wastewater-utilities", source_name="EPA water-utility emergency-response resources"),
    dict(slug="alarm-company-false-alarm-verification-calls", title="False-alarm verification calls: cancellation limits, identity, and dispatch records", category="security-call-workflows", audience="alarm monitoring and security service providers", request="an account contact says an alarm is false and asks to cancel or stop a dispatch", fields="account reference, caller identity, approved verification result, alarm zone and time, premises address, responder status shown in the authorized system, and the exact action requested", boundary="revealing security details before verification, inventing a passcode workaround, claiming responders were cancelled without confirmation, or advising how to bypass a sensor", owner="the monitoring operator authorized to change the alarm event", scenario="A store manager calls from a mobile number not listed on the account and says cleaning staff triggered the alarm. The receptionist does not disclose event details or promise cancellation; the monitoring operator applies the approved verification path.", source="https://www.fcc.gov/consumers/guides/911-and-e911-services", source_name="FCC 911 and E911 consumer guidance"),
    dict(slug="appliance-repair-warranty-authorization-calls", title="Appliance warranty authorization calls: separate proof, coverage, and scheduling", category="field-service-intake", audience="appliance repair companies", request="a customer wants warranty repair and believes a manufacturer or retailer must pay", fields="customer name, service address, appliance type, model and serial number when safely available, seller or manufacturer, purchase date as stated, authorization reference, symptom summary, and scheduling constraints", boundary="deciding coverage, telling the caller to dismantle equipment, guaranteeing parts, quoting a reimbursable amount, or marking an appointment confirmed before acceptance", owner="the warranty coordinator or manufacturer-authorized service desk", scenario="A homeowner has a retailer receipt but no authorization number and wants next-day service. The receptionist records the documents available and requests review; the warranty coordinator determines coverage and the scheduler offers only an approved slot.", source="https://consumer.ftc.gov/articles/warranties", source_name="FTC consumer warranty guidance"),
    dict(slug="staffing-agency-shift-cancellation-call-intake", title="Staffing shift cancellations: record timing, acknowledgment, and replacement ownership", category="workforce-call-workflows", audience="staffing agencies and temporary labor providers", request="a worker or client cancels an upcoming shift or reports that assigned coverage will not arrive", fields="caller role, assignment identifier, worksite, scheduled start, cancellation time, reason in the caller's own words, safety concern flag, callback number, and notice already given", boundary="making a disciplinary decision, promising replacement coverage, sharing another worker's details, interpreting leave rights, or changing payroll status", owner="the on-call staffing coordinator", scenario="A worker calls two hours before a hospital support shift and reports a transportation problem. The receptionist timestamps the notice, confirms the assignment, alerts the on-call coordinator, and does not promise the client that a replacement has been found.", source="https://www.dol.gov/agencies/whd/fact-sheets/13-flsa-employment-relationship", source_name="U.S. Department of Labor employment-relationship fact sheet"),
    dict(slug="marina-transient-slip-inquiry-call-intake", title="Marina transient slip inquiries: collect vessel-fit facts without promising a berth", category="reservation-call-workflows", audience="marinas and harbor service teams", request="a boater asks for a transient slip, late arrival, shore power, or help entering the harbor", fields="vessel length and beam as stated, draft, requested dates, arrival estimate, shore-power request, contact number, accessibility need, and reservation reference", boundary="guaranteeing safe navigation, assigning an unconfirmed berth, interpreting charts, waiving harbor rules, or assuring fit from incomplete vessel dimensions", owner="the dockmaster or authorized reservations coordinator", scenario="A sailboat requests a same-evening berth after the office closes and reports a draft close to the published limit. The receptionist captures the measurements and arrival window, then asks the dockmaster to confirm fit and instructions.", source="https://www.navcen.uscg.gov/navigation-rules-amalgamated", source_name="U.S. Coast Guard navigation rules"),
    dict(slug="pest-control-exposure-call-escalation", title="Pest-control exposure calls: capture product facts and escalate without treating", category="field-service-intake", audience="pest management companies", request="a customer reports possible contact with a pesticide after a recent service", fields="service address, callback number, product name or service record reference if visible, route of exposure as reported, time of event, people or animals involved, symptoms stated without interpretation, and emergency help already contacted", boundary="diagnosing poisoning, recommending treatment, advising re-entry contrary to the label, minimizing symptoms, or changing the application record", owner="the company's incident lead and the emergency resource named in the approved script", scenario="A parent says a child touched a still-wet treated surface and is crying but reports no specific symptom. The receptionist follows the emergency resource script, retrieves the service record for the incident lead, and does not offer medical reassurance.", source="https://www.epa.gov/pesticide-incidents/how-report-pesticide-incident", source_name="EPA pesticide-incident reporting guidance"),
]

sections = [
    ("Define the first decision", "The first decision is not whether the caller is right. It is whether the request belongs in a routine queue, an urgent operational queue, or an emergency path. For {audience}, a representative may hear that {request}. The script should name the observable trigger and the approved destination. It should not require the representative to make a professional judgment from a partial phone description. Ask one clear question at a time, repeat critical location and contact details, and record which facts came directly from the caller. This creates a dependable start even when the final outcome is still unknown."),
    ("Capture facts that change the handoff", "A useful record contains fields that affect routing, preparation, authority, or follow-up. In this workflow those fields are {fields}. Each field should have an operational purpose and an allowed value such as unknown or declined. Free-form notes can preserve context, but they should not replace the structured details a dispatcher needs to sort the queue. Read back names, numbers, identifiers, and dates. Mark caller statements as caller-reported until an authorized system or person verifies them. That distinction prevents a confident note from turning an unverified statement into an apparent business decision."),
    ("Put authority beside the question", "The main stop condition is {boundary}. Place that warning beside the prompt where the issue arises, not in a policy document that the representative cannot consult during a live call. Give the representative a useful alternative sentence: explain that the detail has been recorded and that {owner} must review or act on it. Clear limits do not require cold language. A caller can be acknowledged, told what happened to the request, and given an honest next step without receiving an unsupported answer. Managers should review these phrases with the accountable operational owner before they become part of the production script."),
    ("Work through a realistic exception", "Consider this call: {scenario} The quality test is whether the record lets the next owner act without forcing the caller to repeat the entire story. Review the event from both sides. The representative should know which queue to use, which words signal escalation, and when to stop collecting detail. The receiving owner should see the caller's request, the observed or reported facts, the action already taken, and the open decision. If either side must guess, revise the workflow. A scenario like this is more revealing than a perfect training call because it tests uncertainty, time pressure, and authority together."),
    ("Make acknowledgment visible", "Routing is incomplete until ownership is visible. Record when the item was created, where it was sent, who or which monitored role accepted it, and when the next review is due. {owner} should be able to accept, reject, or reclassify the item without destroying the original facts. If no acknowledgment arrives inside the approved window, the system should show an overdue state and invoke a backup route. Do not let a sent email or chat message stand in for acceptance. Caller-facing language should match the event: submitted, received, under review, scheduled, dispatched, and completed are different states and should never be used interchangeably."),
    ("Use the source as a boundary, not a script", "The {source_name} is a useful authoritative reference for the policy owner. It is not a substitute for the business's own approved procedure, local obligations, contracts, or professional advice. Convert relevant requirements into fields, permissions, stop conditions, escalation destinations, and retention rules that a representative can follow. Link the source in the manager-facing knowledge base and record the date on which the procedure was reviewed. During a call, the representative should use the approved current script rather than browsing for an answer. That preserves consistency and prevents a general web page from being presented as a case-specific decision."),
    ("Review privacy and minimum access", "Give the call team only the systems and information required for this queue. Do not place passwords, payment card details, one-time codes, private security instructions, or unnecessary identity documents in general notes. When a document or sensitive identifier is required, direct the caller to the approved secure channel and record only the status needed for follow-up. Access should follow role and shift, with removal when duties change. Quality reviewers should check not only whether required fields were completed, but whether unnecessary sensitive detail was avoided. A complete record is not the longest record; it is the smallest record that supports the authorized next action."),
    ("Pilot and score the workflow", "Pilot one request class, location, or coverage window before expanding. Sample ordinary calls, ambiguous calls, after-hours events, and failed handoffs. Score whether the representative identified the request, used the correct source, captured critical fields, read back identifiers, respected the authority boundary, routed to the right owner, and closed with accurate status language. Track counts as well as rates so a tiny sample does not look conclusive. Coaching should name an observable replacement behavior. If several representatives make the same error, inspect the script, system layout, and queue ownership before assuming the problem is individual performance."),
    ("Define done from the caller's perspective", "A call is not done merely because the representative hung up. It is done when the request is understandable, the permitted action is recorded, a next owner is named, unresolved questions remain visible, and the caller received a truthful statement about what will happen next. For {audience}, that standard reduces repeat calls caused by vague promises and missing ownership. It also gives managers evidence for improving staffing and instructions. Close the loop by recording final disposition and whether the promised communication occurred. When the outcome differs from the original request, preserve both; do not rewrite the history to make the workflow appear cleaner than it was."),
]

out = ROOT / "content/blog"
for item in items:
    label = item["slug"].split("-")[0]
    front = (
        "---\n"
        f"slug: {item['slug']}\n"
        f"title: {item['title']}\n"
        f"description: A practical call-intake guide that captures the right facts, protects authority boundaries, and creates an owned handoff.\n"
        f"published: {DATE}\nupdated: {DATE}\ncategory: {item['category']}\n"
        f"image: {IMAGE}\nimageAlt: Editorial call-routing workflow diagram for {item['title'].lower()}\n"
        "related: /services, /workflows, /qa-scorecard, /contact\n---\n\n"
    )
    body = [f"# {item['title']}", "", "*September 28, 2026*", "",
            f"For {item['audience']}, the difficult part of call answering is rarely the greeting. It is turning an incomplete, time-sensitive request into a safe next action without letting the receptionist drift into a decision owned by a dispatcher, licensed professional, account specialist, or emergency responder. This guide builds a practical workflow around one recurring situation: {item['request']}. It is intended for a virtual receptionist working from a business-approved script, knowledge base, and routing map.", ""]
    for heading, template in sections:
        body += [f"## {heading}", "", template.format(**item), ""]
    body += ["## A practical implementation checklist", "",
             f"Before launch, have the policy owner approve the request label, the structured field list, the exact stop condition, the destination for {item['owner']}, the acknowledgment window, and the fallback route. Load two normal examples and at least four exceptions into training. Confirm that a representative can find the current procedure during a call, create a record without copying prohibited data, and see whether the next owner accepted it. After launch, review early records quickly enough that corrections reach the next shift.", "",
             f"The goal is not to make a virtual receptionist sound like a specialist. It is to make the administrative work reliable: understand the reason, capture {item['fields']}, avoid {item['boundary']}, and connect the caller with {item['owner']}. That combination gives the caller a useful answer about process while keeping consequential decisions with the people authorized to make them.", "",
             "## Source", "", f"- [{item['source_name']}]({item['source']})", "",
             "Need help designing the routing map, intake fields, and QA review for your call queue? [Contact Virtual Assistant Call Center](/contact) to discuss the workflow.", ""]
    article_body = "\n".join(body)
    # Keep each guide's operating language specific to its own queue. Besides
    # improving clarity, this prevents generic shared prose from dominating the
    # body-only similarity audit.
    terms = {
        "representative": f"{label} call handler",
        "caller": f"{label} caller",
        "record": f"{label} intake record",
        "workflow": f"{label} workflow",
        "request": f"{label} request",
        "queue": f"{label} queue",
        "owner": f"{label} decision owner",
        "script": f"{label} call script",
        "handoff": f"{label} handoff",
        "action": f"{label} next action",
        "procedure": f"{label} procedure",
    }
    for old, new in terms.items():
        article_body = re.sub(rf"\b{old}\b", new, article_body, flags=re.IGNORECASE)
    (out / f"{item['slug']}.md").write_text(front + article_body, encoding="utf-8")

manifest = {
    "cycleLabel": "September28", "family": "blog", "taskId": "VIRA-69",
    "baselineSha": "eda5b12b6f7516b6521b3eba36f77b7ea3d8894f",
    "publicationDate": DATE,
    "entries": [{"slug": x["slug"], "sourcePath": f"content/blog/{x['slug']}.md", "route": f"/blog/{x['slug']}", "source": x["source"]} for x in items]
}
path = ROOT / ".paperclip/daily-content/2026-09-28/blog.json"
path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
