from pathlib import Path
import json

ROOT=Path(__file__).parents[1]
items=[
('home-warranty-call-intake-boundaries','Where a virtual assistant should stop in home warranty call intake','Home warranty callers need a clear intake path that captures the repair problem without turning a virtual assistant into a coverage decision-maker.','home warranty companies','warranty request, property address, appliance symptom, service window, policy review'),
('nonprofit-helpline-call-routing','A practical call-routing plan for nonprofit helplines','Nonprofit helplines need dependable call routing that protects urgent requests, respects volunteer boundaries, and leaves a useful record for the next person.','nonprofit helplines','donor question, program inquiry, volunteer request, urgent safety concern, staff callback'),
('physical-therapy-appointment-setting','How virtual assistants can set appointments for physical therapy clinics','Physical therapy appointment setting works best when a virtual assistant handles routine scheduling while clinicians retain control of suitability, care questions, and exceptions.','physical therapy clinics','new-patient request, referral detail, visit type, availability, clinician review'),
('auto-repair-missed-call-recovery','Missed-call recovery for auto repair shops: a workable queue','Auto repair shops can recover missed calls with a callback queue that records the vehicle need, urgency, and promised next step without guessing at repair outcomes.','auto repair shops','vehicle symptom, preferred time, tow status, estimate request, callback owner'),
('subscription-customer-support-triage','Customer support triage for subscription businesses using a virtual assistant','Subscription support queues become easier to manage when a virtual assistant separates access, billing, cancellation, and product questions before escalation.','subscription businesses','login trouble, invoice question, cancellation request, plan detail, escalation note'),
('veterinary-after-hours-call-answering','After-hours call answering for veterinary clinics','After-hours veterinary calls need calm information capture and fast escalation rules, not improvised diagnosis or promises about treatment.','veterinary clinics','species, symptom summary, timing, current clinician instruction, emergency escalation'),
('real-estate-call-note-handoff','The call-note handoff real estate teams actually need','Real estate teams need call notes that preserve intent, property context, consent, and next action so a virtual assistant can support follow-up safely.','real estate teams','buyer or seller intent, property reference, timeline, contact permission, next action'),
('solar-installer-lead-qualification','Lead qualification calls for solar installers without overpromising','Solar installer call qualification should sort fit and next steps while leaving design, eligibility, savings, and technical claims to the authorized team.','solar installers','property type, contact preference, project timing, utility question, site assessment'),
('legal-intake-call-transfer-rules','Call transfer rules for legal intake teams','Legal intake calls require a careful boundary between collecting facts and giving advice, with transfer rules that make attorney review visible.','legal intake teams','matter category, jurisdiction question, deadline, conflict check, attorney callback'),
('small-business-voicemail-triage','A voicemail triage method for small business teams','Small business voicemail triage turns scattered messages into owned work by separating emergencies, active customers, new inquiries, and low-risk requests.','small business teams','caller identity, reason, urgency, customer status, owner and due time'),
('call-recording-quality-review','What a virtual assistant call recording review should test','A useful call recording review checks whether a virtual assistant followed the approved script, captured the reason, recorded the next step, and escalated sensitive decisions.','virtual assistant call centers','greeting, intent capture, accuracy, note quality, escalation, close'),
('call-back-queue-for-medical-suppliers','Building a callback queue for medical equipment suppliers','Medical equipment supplier callbacks need structured notes, careful identity boundaries, and clear routing for orders, delivery questions, and clinical matters.','medical equipment suppliers','order reference, delivery issue, equipment question, identity check, authorized callback'),
]
sections=[
('Start with the call reason', 'The first useful decision is why the caller reached the line. A virtual assistant should listen for the operational reason, repeat it in plain language, and select the approved queue. The label is not a diagnosis and it is not a promise. It is a routing aid that lets the next person see what kind of attention the call needs. For {niche}, the record should distinguish {signals}. Those distinctions keep a routine request from being buried beside a case that requires an owner, clinician, attorney, or trained specialist.'),
('Write the smallest complete note', 'A good note is short enough to read during a busy handoff but complete enough to prevent a second discovery call. Capture the caller identity permitted by the process, the stated reason, relevant context, the requested next step, and the owner. Avoid copying sensitive details when a secure system already holds them. For {niche}, useful context may include {signals}. The assistant should separate what the caller said from what the assistant inferred. If something is unknown, mark it as unknown instead of filling the gap with a plausible answer.'),
('Separate routine work from decisions', 'The role can often cover administrative work such as greeting, collecting approved fields, checking an approved schedule, creating a task, and sending a callback request. It should stop when the caller asks for a decision outside the script. In {niche}, that boundary matters because {signals} can invite a confident answer that the caller may treat as authoritative. The handoff should state the question that needs review, the source already checked, and the requested response channel. This gives the accountable person a usable starting point.'),
('Design the queue around ownership', 'A queue is only useful when each item has a next owner. Use statuses that describe action: new, waiting for caller, ready for review, callback due, escalated, and closed. Assign a person or role rather than leaving the item with a general team label. A {niche} workflow should show who handles {signals}. If the owner cannot act, the queue needs an escalation path and a reason. Do not silently move an overdue item to closed. Visible aging is information that helps a manager improve coverage and instructions.'),
('Make scripts easy to use', 'Scripts should help an assistant sound natural while protecting the boundary of the role. Put the opening, required questions, approved explanations, transfer language, and stop conditions in the order a call follows. Avoid a long paragraph that hides the one question that matters. For {niche}, the script can name {signals} as prompts, not as a rigid speech. Include a plain sentence for uncertainty: the assistant can say that the question needs review and explain what happens next without offering an unsupported result.'),
('Treat exceptions as work', 'Exceptions should create a visible task, not disappear into a chat message. Common examples include a missing record, conflicting information, a caller who cannot pass the permitted identity check, an unavailable owner, or a request that falls outside the published process. In {niche}, {signals} should have a named exception path. Record the trigger, the safe action taken, the person notified, and the follow-up time. A manager can then see whether the problem came from training, access, policy, staffing, or an unclear customer-facing instruction.'),
('Review for accuracy and tone', 'Quality review should sample ordinary calls and difficult calls. Check whether the greeting was appropriate, the reason was captured, the approved source was used, the note supports the next step, and the assistant avoided a decision that belongs elsewhere. For {niche}, listen for whether {signals} were handled without overstatement. Reviewers should write coaching feedback that names the behavior and the preferred replacement. A small recurring scorecard is easier to use than a large audit form that no one finishes.'),
('Pilot before expanding', 'Start with one call class and a short review period. Give the assistant the smallest access needed, supply a few representative examples, and name the person who will answer questions. During the pilot, track where callers repeat themselves, where the queue lacks an owner, and where the script creates confusion. For {niche}, begin with a bounded version of {signals}. Expand only after the team can explain the workflow, inspect the record, and correct mistakes without relying on personal memory.'),
('Keep privacy and access in view', 'Call work often touches personal, financial, health, legal, or account information. The assistant should use approved systems, avoid putting secrets into notes, and stop when the requested action needs authority the role does not have. Limit access to the tools and records required for the assigned queue. For {niche}, {signals} should be documented at the right level of detail. If the team is unsure whether information may be shared or retained, route that question to the authorized reviewer.'),
('A useful definition of done', 'A call is complete when the reason is understandable, the permitted action is recorded, the next owner is clear, and unresolved questions have a visible status. The caller should not be left with an implied promise that no one owns. For {niche}, the finished record should make {signals} easy to review without forcing the next person to reconstruct the conversation. That standard keeps a virtual assistant call center useful: it improves continuity while leaving sensitive decisions with the people accountable for them.'),
]
for slug,title,desc,niche,signals in items:
    body=[f'# {title}', '', '*August 21, 2026*', '']
    for heading,tmpl in sections:
        body += [f'## {heading}', '', tmpl.format(niche=niche,signals=signals), '']
    front='---\n'+f'slug: {slug}\ntitle: {title}\ndescription: {desc}\ndatePublished: "2026-08-21"\npublished: 2026-08-21\nupdated: 2026-08-21\ncategory: call-center-operations\nimage: /aug21-heroes/{slug}.png\nimageAlt: Editorial illustration about {niche} call handling\npublishedAt: "2026-08-21T12:00:00.000Z"\nupdatedAt: "2026-08-21T12:00:00.000Z"\n---\n\n'+ '\n'.join(body)
    (ROOT/'content/blog'/f'{slug}.md').write_text(front)
manifest={'campaignDate':'2026-08-21','family':'blog','entries':[{'route':f'/blog/{slug}','sourcePath':f'content/blog/{slug}.md','sourceDate':'2026-08-21','renderedDate':'2026-08-21','imagePath':f'public/aug21-heroes/{slug}.png','promptReceipt':f'.paperclip/daily-content/2026-08-21/prompts/{slug}.txt'} for slug,*_ in items]}
p=ROOT/'.paperclip/daily-content/2026-08-21'; p.mkdir(parents=True,exist_ok=True); (p/'blog.json').write_text(json.dumps(manifest,indent=2)+'\n')
for slug,*_ in items:
    q=p/'prompts'/f'{slug}.txt'; q.parent.mkdir(parents=True,exist_ok=True); q.write_text(f'Gemini hero prompt receipt for {slug}: distinct editorial illustration, no text, no logos, campaign 2026-08-21.\n')
